### ISSUE TITLE
Кавычки не нужны

### ISSUE THREAD

**Issue by ilyaevseev** [alexDraven23/My-first-bot#2]
https://github.com/alexDraven23/My-first-bot/blob/86ed731996a55e676a153d29de0dc08da6dd1bb8/Bot1.py#L7

Кавычки не нужны.

Попробуйте такой пример, можно прямо в интерактивном режиме Питона:

```
a = '123'
b = a
c = 'a'
print(a,b,c)
```

**Comment by alexDraven23** [comment]
Fix #2 - Remove quotes around tgtoken in 82ecb7e
