### ISSUE TITLE
Зависимость от версии лучше сменить на нестрогую.

### ISSUE THREAD

**Issue by ilyaevseev** [alexDraven23/My-first-bot#6]
https://github.com/alexDraven23/My-first-bot/blob/b7be583df6053665fe7f7d009b380f255dba65ad/requirements.txt#L1

Я бы попробовал указать версию не строго, а как минимальную.

Строгие версии и "pip freeze" хороши в проектах с десятками зависимостей типа Django.

В мелких проектах лучше использовать свежие версии пакетов вместо фиксированных устаревших.

**Comment by ilyaevseev** [comment]
Закрыть лучше было с комментарием:

> WONTFIX - requirements are generated by pipreqs

Если закрываете молча, могут неправильно понять.

**Comment by alexDraven23** [comment]
Окей, буду знать
